#Installs all software groups
& "$PSScriptRoot\Software\2Dgraphics.ps1"
& "$PSScriptRoot\Software\3Dgraphics.ps1"
& "$PSScriptRoot\Software\communications.ps1"
& "$PSScriptRoot\Software\dev_full.ps1"
& "$PSScriptRoot\Software\ebooks.ps1"
& "$PSScriptRoot\Software\hardwareMonitoring.ps1"
& "$PSScriptRoot\Software\maintenance.ps1"
& "$PSScriptRoot\Software\tools.ps1"
& "$PSScriptRoot\Software\toolsOptional.ps1"
& "$PSScriptRoot\Software\video.ps1"
